#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/NetRobotArm.jar:$APPDIR/lib/core.jar:$APPDIR/lib/WebSocket.jar:$APPDIR/lib/net.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/Arduino.jar" NetRobotArm
